#ifndef SABER_PARAMS_H
#define SABER_PARAMS_H

#include "../../SABER/Reference_Implementation_KEM/SABER_params.h"

#define SABER_PUBLIC_KEY_BYTES   SABER_INDCPA_PUBLICKEYBYTES
#define SABER_CIPHERTEXT_BYTES   (SABER_BYTES_CCA_DEC + SABER_HASHBYTES)
#define SABER_SHARED_KEY_BYTES   SABER_KEYBYTES

#define MSG_BYTES                SABER_KEYBYTES
#define D_BYTES                  SABER_KEYBYTES
#define Z_BYTES                  SABER_KEYBYTES
#define NOISE_BYTES              SABER_NOISE_SEEDBYTES

#define SK_CORE_BYTES    (SABER_INDCPA_SECRETKEYBYTES + Z_BYTES)
#define PK_BYTES         SABER_INDCPA_PUBLICKEYBYTES
#define CT_CORE_BYTES    SABER_BYTES_CCA_DEC

#define SABER_SECRET_KEY_BYTES   (SK_CORE_BYTES + SABER_PUBLIC_KEY_BYTES)


#endif //SABER_PARAMS_H
